'use strict';(()=>{parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-xs"));const e=16*parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-sm")),f=16*parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-md")),h=16*parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-lg")),g=16*parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-xl"));parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-xxl"));
const b=()=>{(()=>{document.querySelectorAll("body > .layout-overlay").forEach(n=>{n.remove()});const p=document.createElement("div");p.className="layout-overlay";document.body.prepend(p)})();(()=>{document.querySelectorAll("body .header__sidebar-nav").forEach(n=>{n.remove()});const p=document.querySelector(".sidebar");if(p){const n=document.querySelector(".header__group"),r=p.dataset.toggleLabel;if(n){const t=document.createElement("button");t.classList="header__sidebar-nav";t.setAttribute("aria-label",
r||"Toggle sidebar");p.classList.contains("sidebar_without-icon")&&t.classList.add("header__sidebar-nav_simple");t.innerHTML='<span class="icon icon-bars-3-bottom-left-solid"></span>';n.prepend(t)}}})();a()},a=()=>{const p=document.querySelector(".sidebar");if(p){let n=0;document.querySelectorAll(".sidebar > *").forEach(r=>{n+=r.offsetHeight});p.classList.remove("sidebar_scroll");p.classList.remove("sidebar_without-scroll");n>p.offsetHeight?p.classList.add("sidebar_scroll"):p.classList.add("sidebar_without-scroll")}},
c=p=>{p.classList.add("expand-enter-active");p.classList.add("sidebar_expanded");setTimeout(()=>{p.classList.remove("expand-enter-active")},350)},d=p=>{p.classList.add("expand-enter-active");p.closest(".sidebar_expanded")&&(p.style.width="0rem",setTimeout(()=>{p.style.width="";p.classList.remove("expand-enter-active");p.classList.remove("sidebar_expanded");document.querySelector(".layout-overlay_content")?.classList.remove("layout-overlay_content")},350))},l=p=>{const n=p.closest('[data-toggle="dropdown-list"]');
if(n){const r=document.querySelector(n.dataset.target);n.closest(".dropdown__list").querySelectorAll('[data-toggle="dropdown-list"]').forEach(t=>{const x=document.querySelector(t.dataset.target);x&&(t.classList.remove("show"),x.classList.remove("show"));x===r&&(n.classList.add("show"),x.classList.add("show"))})}},k=()=>{const p=document.querySelectorAll(".dropdown.dropdown_nav:not(.dropdown_notification)"),n=document.querySelectorAll(".dropdown.dropdown_nav.dropdown_notification");p.forEach(r=>{const t=
r.querySelector(".dropdown__box");if(t&&!t.querySelector(".dropdown__box-header")){r=r.querySelector('[data-toggle="dropdown"]');const x=document.createElement("div");x.classList="dropdown__box-header";x.innerHTML=`
                <span class="icon icon-x-mark-mini" role="button" data-toggle="dropdown"></span>
                <span class="dropdown__box-title">${t.dataset.dropdownTitle??(r?r.textContent?.trim():"")}</span>
            `.trim();t.prepend(x)}});n.forEach(r=>{if(r=r.querySelector(".notification__title")){const t=document.createElement("span");t.classList="icon icon-x-mark-mini";t.dataset.toggle="dropdown";r.prepend(t)}})},m=p=>{const n=document.createElement("li");n.className="nav__item";n.innerHTML=`
            <div class="dropdown dropdown_nav">
                <a class="nav__link nav__link_more active" href="#" data-toggle="dropdown" aria-expanded="false">
                    <span>${p.dataset.moreText??"Lainnya"}</span>
                    <span class="icon icon-chevron-down-mini"></span>
                </a>
                <div class="dropdown__box dropdown__box_multi">
                    <ul class="dropdown__list"></ul>
                </div>
            </div>
        `.trim();p.append(n)},q=(p,n,r,t)=>{p=document.querySelector(".header__navigation .nav__link.nav__link_more").closest(".dropdown");const x=document.querySelector(".header__navigation .nav__link.nav__link_more").closest(".nav__item"),z=n.closest(".dropdown"),A=document.createElement("li");A.className=`
            dropdown__item
            ${""}
            ${n.closest(".nav__item.active")?" active":""}
        `.trim();z?(A.dataset.toggle="dropdown-list",A.dataset.target="#qn-dropdown-list-"+r,A.setAttribute("aria-expanded",r==t?"true":"false"),A.innerHTML=`
                <button>
                    ${n.text.trim()}
                    <span class="dropdown__item-right">
                        <span class="icon icon-arrow-right"></span>
                    </span>
                </button>
            `.trim(),t=z.querySelector(".dropdown__list"),t.classList.add("dropdown__list_hidden"),t.id="qn-dropdown-list-"+r,r=document.createElement("li"),r.className="dropdown__item-title",r.innerHTML=`
                <span class="icon icon-arrow-left-mini" data-hide="dropdown-list"></span>
                <p>${n.text.trim()}</p>
            `.trim(),t.prepend(r),n.closest(".nav__item.active")&&(p.querySelectorAll(".dropdown__box").forEach(B=>{B.classList.remove("show")}),x.classList.contains("active")||x.classList.add("active"),x.querySelectorAll(".dropdown__item.show").forEach(B=>{B.classList.remove("show");document.querySelector(B.dataset.target).classList.remove("show");B.setAttribute("aria-expanded",!1)})),p.querySelector(".dropdown__box").append(t),n.remove()):(n.closest(".nav__item.active")&&!x.classList.contains("active")&&
x.classList.add("active"),n.classList.remove("nav__link"),A.append(n));p.querySelector(".dropdown__list:not(.dropdown__list_hidden)").append(A)},v=(p,n=!1)=>{document.querySelectorAll(".header__navigation .nav__link:not(.nav__link_more)").forEach((r,t)=>{t+=1;t>=p&&q(n,r,t,p)})},u=(p,n=!1)=>{document.querySelector(".header__navigation .nav__link.nav__link_more");document.querySelectorAll(".header__navigation .nav__link:not(.nav__link_more)").forEach((r,t)=>{r.closest(".dropdown");t+=1;t>=p&&q(n,r,
t,p)})},w=()=>{const p=document.querySelector(".header__navigation .nav__list"),n=document.querySelectorAll(".header__navigation .nav__link:not(.nav__link_more)"),r=document.querySelector(".header__navigation .nav__link.nav__link_more");r?r&&(document.body.clientWidth>=g?6<n.length&&u(6):document.body.clientWidth>=h?5<n.length&&u(5):document.body.clientWidth>=f?4<n.length&&u(4):document.body.clientWidth>=e?3<n.length&&u(3):2<n.length&&u(2,!0)):document.body.clientWidth>=g?6<n.length&&(m(p),v(6)):
document.body.clientWidth>=h?5<n.length&&(m(p),v(5)):document.body.clientWidth>=f?4<n.length&&(m(p),v(4)):document.body.clientWidth>=e?3<n.length&&(m(p),v(3)):2<n.length&&(m(p),v(2,!0))},y=()=>{var p=document.querySelector(".form-nav__button-wrapper");const n=document.querySelector(".form-table"),r=document.querySelector(".main > form");if(r&&(n||p)){document.querySelector(".form-table_sticky-bottom")?.remove();const t=document.createElement("div");t.className="form-table form-table_sticky-bottom";
const x=document.createElement("div");x.className="form-table__wrapper";if(n){const z=document.createElement("div");z.className="collapse";z.id="qn-form-table-sticky";z.innerHTML=n.innerHTML;t.append(z);x.innerHTML+=`
                    <button type="button" class="btn btn_secondary btn_icon" data-toggle="collapse" data-target="#${z.id}" aria-expanded="false">
                        <span class="icon icon-list-bullet-mini"></span>
                    </button>
                `.trim()}p&&(p=p.cloneNode(!0),p.className="form-table__button-wrapper",p.setAttribute("data-placement","top"),x.append(p));t.append(x);r.append(t)}};document.addEventListener("click",p=>{p=p.target;var n=document.querySelector(".layout-overlay"),r=document.querySelector(".sidebar");const t=document.querySelector(".form-table_sticky-bottom");p.closest(".layout-overlay")&&(n?.classList.remove("layout-overlay_main"),r&&d(r),t&&t.querySelector('[data-toggle="collapse"].show')?.click());
p.closest(".header__sidebar-nav")&&(n=document.querySelector(".sidebar"))&&(n.classList.contains("sidebar_expanded")?d(n):c(n),a());(n=p.closest(".form-table__title .icon"))&&!n?.closest(".form-table_sticky-bottom")&&(n=n.closest(".form-table"))&&(n.classList.contains("form-table_collapse")?n.classList.remove("form-table_collapse"):n.classList.add("form-table_collapse"));l(p);(n=p.closest('[data-hide="dropdown-list"]'))&&n.closest(".dropdown__list")&&n.closest(".dropdown__list").classList.remove("show");
n=p.closest(".form-table_sticky-bottom");r=p.closest(".form-table__item");p=p.closest(".form-table__title  .icon");n&&(r||p)&&n.querySelector('[data-toggle="collapse"].show')?.click()});document.addEventListener("DOMContentLoaded",p=>{document.querySelector(".header__navigation .nav__list")&&document.querySelector(".header__navigation .nav__list").cloneNode(!0);b();w();k();y();document.addEventListener("click",n=>{(n=n.target.closest("[data-click-for]"))&&(n=n.dataset.clickFor)&&document.querySelector(n)&&
document.querySelector(n).click();n=document.querySelector(".layout-overlay");var r=document.querySelector('.form-table_sticky-bottom [data-toggle="collapse"]');r&&(r.classList.contains("show")?n.classList.add("layout-overlay_form-content"):n.classList.remove("layout-overlay_form-content"));(r=document.querySelector(".header"))&&(0<r.querySelectorAll(".dropdown__box.show:not(.dropdown__list_hidden), .dropdown__box.show:not(.dropdown__list_hidden)").length?n.classList.add("layout-overlay_main"):n.classList.remove("layout-overlay_main"));
(r=document.querySelector(".sidebar"))&&(r.classList.contains("sidebar_expanded")?n.classList.add("layout-overlay_content"):n.classList.remove("layout-overlay_content"))})});(()=>{(new MutationObserver((p,n)=>{for(const r of p)"childList"===r.type&&r.addedNodes.forEach(t=>{t.classList&&(t.classList.contains("header")||t.classList.contains("sidebar"))&&(b(),w())})})).observe(document.body,{childList:!0,subtree:!0})})();window.addEventListener("resize",()=>{w();a()});document.addEventListener("mouseover",
p=>{(p=p.target.closest('.dropdown__item[data-toggle="dropdown-list"]'))&&document.body.clientWidth>=e&&p.click()})})();
(()=>{const e=()=>{const d=document.querySelectorAll(".form-table__title");0<d.length&&d.forEach(l=>{var k=l.querySelector(".icon");k&&k.remove();k=document.createElement("span");k.classList.add("icon");l.append(k)})},f=()=>{var d=document.querySelector(".form-table:not(.form-table__sticky-bottom)");let l=document.querySelector(".form-nav");var k=document.querySelector(".form-nav ~ .container .breadcrumb"),m=document.querySelector(".header");let q=document.querySelector(".header.header_position-static");
if(d){let v=0;m&&(v+=m.getBoundingClientRect().height);l&&(v+=l.getBoundingClientRect().height);if(q){let u=q.getBoundingClientRect();v=0<=u.bottom?v-(u.height-u.bottom):v-u.height}d.style.top=v+"px"}l&&k&&(d=0,m&&(d+=m.getBoundingClientRect().height),l&&(d+=l.getBoundingClientRect().height),q&&(m=q.getBoundingClientRect(),d=0<=m.bottom?d-(m.height-m.bottom):d-m.height),k=0>=k.getBoundingClientRect().bottom-d?1:0,l.querySelector(".form-nav__middle").style.opacity=k)},h=()=>{if(document.querySelector(".form-table ~ .container")){let d=
window.location.href;const l=()=>{document.querySelectorAll(".form-table__list > .form-table__item:first-child .form-table__anchor").forEach(k=>{k?.click()});window.scrollTo({top:0,behavior:"smooth"})};try{let k=(new URL(d)).hash.substring(1).replace(/\/\s*$/,"");k?document.querySelectorAll("[href='#"+k+"']").forEach(m=>{m?m.click():l()}):l()}catch(k){l()}}},g=d=>{document.querySelector(".form-table ~ .container")&&d.closest(".container")&&(d=d.closest(".card"))&&(d.closest(".container").querySelectorAll(".card").forEach(l=>
{l.classList.remove("card_highlight")}),d.classList.add("card_highlight"),d.id&&(d=document.querySelectorAll("[href='#"+d.id+"']"))&&d.forEach(l=>{l.closest(".form-table").querySelectorAll(".form-table__item").forEach(k=>{k.classList.remove("active")});l.closest(".form-table__item")?.classList.add("active")}))},b=d=>0===d.replace(/<(?:.|\n)*?>/gm,"").trim().length&&!d.includes("<img"),a=()=>{document.querySelectorAll(".text-editor").forEach(d=>{const l=Quill.find(d);if(l)l.on("text-change",function(){const k=
b(l.root.innerHTML)?"":l.root.innerHTML,m=document.querySelector(".form-control textarea[hidden]");m&&(m.value=k,m.dispatchEvent(new Event("input",{bubbles:!0})));c()})});c()},c=()=>{document.querySelectorAll("form [type='submit']").forEach(d=>{let l=d.closest("form");if(l){let k=!1;l.querySelectorAll("input:required, select:required, textarea:required").forEach(m=>{"checkbox"===m.type?m.checked||(k=!0):""===m.value&&(k=!0)});l.querySelectorAll(".text-editor").forEach(m=>{(m=Quill.find(m))&&b(m.root.innerHTML)&&
(k=!0)});k&&document.querySelector(".form-nav")?(d.parentNode.dataset.tooltip="Pastikan semua inputan mandatori telah diisi",d.parentNode.dataset.placement="left",d.closest(".form-table_sticky-bottom")&&(d.parentNode.dataset.placement="top")):d.parentNode.removeAttribute("data-tooltip");d.disabled=k}})};document.addEventListener("DOMContentLoaded",d=>{e();f();c();h();a()});window.addEventListener("scroll",d=>{f()});document.addEventListener("change",d=>{c()});document.addEventListener("input",d=>
{c()});document.addEventListener("focusin",d=>{g(d.target)});document.addEventListener("click",d=>{let l=d.target;g(l);if(l.closest('a[href^="#"]')){d.preventDefault();let k="#"!=l.closest('a[href^="#"]')?.getAttribute("href")?document.querySelector(l.closest('a[href^="#"]')?.getAttribute("href")):!1;if(k){d=k.getBoundingClientRect().top-72+(window.pageYOffset||document.documentElement.scrollTop);let m=l.closest(".form-table");k.classList.contains("card")&&m&&k.closest(".container")&&(m.querySelectorAll(".form-table__item").forEach(q=>
{q.classList.remove("active")}),l.closest('a[href^="#"]').closest(".form-table__item")?.classList.add("active"),k.closest(".container").querySelectorAll(".card").forEach(q=>{q.classList.remove("card_highlight")}),setTimeout(()=>{k.classList.add("card_highlight")},150));window.scrollTo({top:d,behavior:"smooth"})}}})})();
(()=>{const e=()=>{const a=document.querySelectorAll(".header_template");0<a.length&&a.forEach(c=>{var d=c.querySelector(".header__group");if(d){var l=c.querySelector(".header__row-wrapper:not(.header__row-wrapper_nav)"),k=window.getComputedStyle(l);c=parseFloat(k.paddingTop);k=parseFloat(k.paddingBottom);l=l.offsetHeight;d=d.offsetHeight;document.body.style.setProperty("--qn-semantic-header-row-wrapper-height","");d>l-c-k&&document.body.style.setProperty("--qn-semantic-header-row-wrapper-height",
d+c+k+"px")}})};let f="";const h=()=>{const a=document.querySelector(".header__row-wrapper_nav");var c=a.querySelector(".nav__list");const d=window.getComputedStyle(a);c=window.getComputedStyle(c);return{"padding-left":parseFloat(d.paddingLeft)??0,"padding-right":parseFloat(d.paddingRight)??0,"padding-x":(parseFloat(d.paddingLeft)??0)+(parseFloat(d.paddingRight)??0),gap:parseFloat(c.gap)??0,width:a.clientWidth??0}},g=(a,c,d=100)=>{const l=a.querySelector(".nav__link");let k=!1;var m=16*parseFloat(getComputedStyle(document.body).getPropertyValue("--qn-breakpoint-sm"));
document.body.clientWidth<m&&(k=!0);m=document.querySelector(".header__row-wrapper_nav .nav__link.nav__link_more").closest(".dropdown");const q=document.querySelector(".header__row-wrapper_nav .nav__link.nav__link_more").closest(".nav__item"),v=l.closest(".dropdown"),u=document.createElement("li");u.className=`
            dropdown__item
            ${v&&!k&&1==c?" show":""}
            ${l.closest(".nav__item.active")?" active":""}
        `.trim();v?(u.dataset.toggle="dropdown-list",u.dataset.target="#qn-dropdown-list-"+c,u.setAttribute("aria-expanded",c==d?"true":"false"),u.innerHTML=`
                <button>
                    ${l.text.trim()}
                    <span class="dropdown__item-right">
                        <span class="icon icon-arrow-right"></span>
                    </span>
                </button>
            `.trim(),d=v.querySelector(".dropdown__list"),d.classList.add("dropdown__list_hidden"),d.id="qn-dropdown-list-"+c,1!=c||k||d.classList.add("show"),c=document.createElement("li"),c.className="dropdown__item-title",c.innerHTML=`
                <span class="icon icon-arrow-left-mini" data-hide="dropdown-list"></span>
                <p>${l.text.trim()}</p>
            `.trim(),d.prepend(c),l.closest(".nav__item.active")&&(m.querySelectorAll(".dropdown__box").forEach(w=>{w.classList.remove("show")}),k||d.classList.add("show"),q.classList.contains("active")||q.classList.add("active"),q.querySelectorAll(".dropdown__item.show").forEach(w=>{w.classList.remove("show");document.querySelector(w.dataset.target).classList.remove("show");w.setAttribute("aria-expanded",!1)})),m.querySelector(".dropdown__box").append(d)):(l.closest(".nav__item.active")&&!q.classList.contains("active")&&
q.classList.add("active"),l.classList.remove("nav__link"),u.append(l));a.remove();m.querySelector(".dropdown__list:not(.dropdown__list_hidden)").append(u)},b=()=>{if(document.querySelector(".header_template")){var a=document.querySelector(".header__row-wrapper_nav");f=a?a.innerHTML:"";var c=document.querySelector(".header__row-wrapper_nav .nav__list"),d=c?c.clientWidth:0;a=h().width-h()["padding-x"];if(d>a){var l=document.createElement("li");l.className="nav__item nav__item_more";l.style.opacity=
"0";l.style.pointerEvents="none";l.innerHTML=`
            <div class="dropdown dropdown_nav">
                <a class="nav__link nav__link_more active" href="#" data-toggle="dropdown" aria-expanded="false">
                    <span>${c.dataset.moreText??"Lainnya"}</span>
                    <span class="icon icon-chevron-down-mini"></span>
                </a>
                <div class="dropdown__box dropdown__box_multi" data-popper-placement="bottom-right">
                    <ul class="dropdown__list"></ul>
                </div>
            </div>
        `.trim();c.append(l);if(l=c.querySelector(".nav__link_more")){var k=l.closest(".dropdown_nav");if(k&&(l=k.querySelector(".dropdown__box"))&&!l.querySelector(".dropdown__box-header")){k=k.querySelector('[data-toggle="dropdown"]');var m=document.createElement("div");m.classList="dropdown__box-header";m.innerHTML=`
                <span class="icon icon-x-mark-mini" role="button" data-toggle="dropdown"></span>
                <span class="dropdown__box-title">${l.dataset.dropdownTitle??(k?k.textContent?.trim():"")}</span>
            `.trim();l.prepend(m)}}l=c.querySelector(".nav__item.nav__item_more");c=Array.from(c.querySelectorAll(".nav__item:not(.nav__item_more)"));k=d;d=[];m=!0;for(let q=c.length-1;0<=q;q--)k-c[q].clientWidth+l.clientWidth>a&&!0===m?(k-=c[q].clientWidth+h().gap,d.push(c[q])):k-c[q].clientWidth+l.clientWidth<a&&!0===m&&(m=!1,d.push(c[q]));for(a=d.length-1;0<=a;a--)g(d[a],d.length-a);l.style.opacity="";l.style.pointerEvents=""}}};document.addEventListener("DOMContentLoaded",a=>{b();e();a=document.body;
const c=document.querySelector(".nav-mobile");a&&c&&a.classList.add("body_has-nav-mobile")});window.addEventListener("resize",a=>{(a=document.querySelector(".header__row-wrapper_nav"))?a.innerHTML=`${f}`:null;b();e()})})();(()=>{document.addEventListener("click",e=>{var f=e.target;e=f.closest(".alert");f=f.closest("[data-dismiss='alert']");e&&f&&e.remove()})})();(()=>{const e=()=>{document.querySelectorAll(".avatar[data-avatar-name], .avatar__circle[data-avatar-name]").forEach(f=>{const h=f.dataset.avatarName;if(h){var g=f.closest(".avatar");g?.querySelector(".avatar__acronym")&&g.querySelector(".avatar__acronym").remove();g=document.createElement("p");g.className="avatar__acronym";let b=h.matchAll(/\b(\w)\w*\b/g);g.innerHTML=1<b.length?b.slice(0,2):h.slice(0,2);f?.append(g)}})};document.addEventListener("DOMContentLoaded",f=>{e()});(new MutationObserver(f=>
{f.forEach(h=>{"attributes"===h.type&&"data-avatar-name"===h.attributeName&&h.target.closest(".avatar")&&e()})})).observe(document.body,{attributes:!0,subtree:!0,attributeOldValue:!0,attributeFilter:["data-avatar-name"]})})();const triggers=document.querySelectorAll('.code__action [data-toggle="collapse"]');triggers.forEach(e=>{e.addEventListener("click",f=>{f=f.target.closest('[data-toggle="collapse"]');const h=f.getAttribute("data-target");collapse(h,"toggle")?(f.style.cssText="background-color: #141414; border-radius: 0.375rem 0.375rem 0 0; color: #fff",f.querySelector(".icon").style.cssText="color: white !important;"):(f.removeAttribute("style"),f.querySelector(".icon").removeAttribute("style"))})});
const fnmap={toggle:"toggle",show:"add",hide:"remove"},collapse=(e,f)=>{e=document.querySelector(e);e.classList[fnmap[f]]("show");return e.classList.contains("show")?!0:!1};
(()=>{const e=(h,g,b,a="show")=>{let c=window.getComputedStyle?getComputedStyle(g,null):g.currentStyle,d=()=>{let l=0;document.querySelectorAll(b+" > *").forEach(k=>{l+=k.getBoundingClientRect().height});l+=parseInt(c.paddingTop,10);l+=parseInt(c.paddingBottom,10);l+=parseInt(c.marginTop,10);return l+=parseInt(c.marginBottom,10)};"show"==a?(h?.classList.add("show"),g.classList.add("expand-enter-active"),h?.setAttribute("aria-expanded",!0),g.classList.add("show"),g.style.height="0",g.style.height=
d()+"px",setTimeout(()=>{g.classList.remove("expand-enter-active");g.style.height="auto"},350)):(h?.classList.remove("show"),g.classList.add("expand-leave-active"),h?.setAttribute("aria-expanded",!1),g.style.height=d()+"px",setTimeout(()=>{g.style.height="0";g.style.paddingTop="0";g.style.paddingBottom="0"}),setTimeout(()=>{g.classList.remove("expand-leave-active");g.style.height="auto";g.style.paddingTop="";g.style.paddingBottom="";g.classList.remove("show")},350))},f=(h,g="toggle")=>{if(h.closest("[data-toggle='collapse']")){h=
h.closest("[data-toggle='collapse']");let b=h.dataset.target,a=document.querySelector(b);("true"==h.getAttribute("aria-expanded")||h.classList.contains("show"))&&a?"toggle"==g?e(h,a,b,"hide"):e(h,a,b,"show"):"toggle"==g?e(h,a,b,"show"):e(h,a,b,"hide")}};document.addEventListener("click",h=>{h=h.target;f(h);if(h=h.closest('[data-close="collapse"]'))if(h=h.closest(".collapse"))(h=h.id)&&(h=document.querySelector('[data-target="#'+h+'"]')),h.click()});document.addEventListener("DOMContentLoaded",h=>
{document.body.querySelectorAll("[data-toggle='collapse']").forEach(g=>{f(g,"check")})})})();class Dropdown{constructor(e,f={}){this.typeList=["select","autocomplete","multiple"];this.element=e;this.type=f?.type?.toLowerCase()??"select";this.id=f?.id??!1;this.class=f?.class??!1;this.tags=f?.tags??!1;this.search=f?.search??!0;this.searchName=f?.searchName??!1;this.searchPlaceholder=f?.searchPlaceholder??"Masukkan kata kunci";this.searchMinimalLength=f?.searchMinimalLength??1;this.noResult=f?.noResult??!0;this.noResultHelper=f?.noResultHelper??`Coba cari dengan kata kunci lain${0!=f?.tags?
", atau tambahkan data baru jika diperlukan":""}.`;this.init();this.typeList}init(){if(this.element&&this.typeList.includes(this.type)&&(this.element.style.display="none",this.element.removeAttribute("tabindex"),!this.element.nextElementSibling?.classList.contains("dropdown"))){var e=this.element.options[this.element.selectedIndex],f=document.createElement("div");f.className=`dropdown dropdown_full-width${this.class?" "+this.class:""}${this.element.classList.contains("error")?" error":""}${this.element.classList.contains("loading")?
" loading":""}`;f.id=this.id?this.id:"";f.innerHTML=(("autocomplete"!=this.type?`<span class="dropdown__text dropdown__selected" data-toggle="dropdown" tabindex="0" aria-expanded="false">${e.innerHTML}</span>`:"")+'<div class="dropdown__box"><ul class="dropdown__list"></ul></div>').trim();this.element.after(f);let h=this.element.nextElementSibling;this.element.querySelectorAll("option").forEach((g,b)=>{g.innerHTML&&(b=document.createElement("li"),b.className=`dropdown__item ${g.selected?"selected ":
""} ${g.disabled?"disabled ":""}`,this.typeList.includes(this.type)&&(b.setAttribute("data-value",g.value),b.setAttribute("data-alt",g.dataset.alt??"")),b.innerHTML=`<button type="button"${g.disabled?" disabled ":""}>`+(g.dataset.imgSrc?`<img src="${g.dataset.imgSrc}" alt="${g.dataset.imgAlt||""}">`:"")+(g.dataset.icon?`<span class="icon icon-${g.dataset.icon}"></span>`:"")+g.textContent+"</button>",h.querySelector(".dropdown__list").appendChild(b))});if(this.typeList.includes(this.type)&&0!=this.noResult){f=
document.createElement("div");f.className="dropdown__empty";const g=this.noResult.button?'<div class="dropdown__empty-action"><button class="btn btn_secondary dropdown__action">Tambahkan Item</button></div>':"";f.innerHTML=('<div class="dropdown__empty-information"><span class="dropdown__empty-title"></span>'+`<p class="dropdown__empty-helper">${this.noResultHelper}</p>`+'</div><div class="dropdown__loader"><div class="dropdown__loader-wrapper"><span class="loader loader_lg"></span></div></div>').trim()+
g.trim();h.querySelector(".dropdown__box").appendChild(f)}if("autocomplete"==this.type||0!=this.search)e='<div class="form-control"><div class="form-control__group"><span data-input-icon="search"></span>'+`<input
                                    type="text"
                                    class="form-control__input"
                                    placeholder="${this.searchPlaceholder?this.searchPlaceholder:""}"
                                    ${this.id?' id="'+this.id+'__search"':""}
                                    ${this.searchName?' name="'+this.searchName+'"':""}
                                    ${"autocomplete"==this.type?'value="'+e.text+'"':""}
                                    autocomplete="off"
                                />`+'<span data-clear="input"></span></div></div>',f=document.createElement("div"),f.className="dropdown__search-box",f.innerHTML=e.trim(),"select"==this.type?h.querySelector(".dropdown__list").before(f):h.innerHTML=f.trim()+h.innerHTML}}setOptions(e=[]){let f=[],h=!0;if("object"==typeof e)f=e,h=!1;else if("function"==typeof e){let g=this.element,b=this.element.nextElementSibling,a=b.querySelector(".dropdown__list");"dynamic"!=a.dataset.dataDropdown&&(a.dataset.dataDropdown=
"dynamic");let c=this.typeList.includes(this.type);a.innerHTML="";const d=document.createElement("li");d.className="dropdown__item";d.innerHTML="<i>Searching</i>";a.appendChild(d);(async function(){f=await e();h=!1;if("object"==typeof f&&!h){a.innerHTML="";f.forEach(k=>{const m=document.createElement("li");m.className=`dropdown__item ${g.value==k.value?"selected ":""} ${k.disabled?"disabled ":""}`;c&&(m.setAttribute("data-value",k.value),m.setAttribute("data-alt",k.alt??""));m.innerHTML=`<button type="button"${1==
k.disabled?" disabled ":""}>
                                ${k.imgSrc?`<img src="${k.imgSrc}" alt="${k.imgAlt||""}">`:""}
                                ${k.icon?`<span class="icon icon-${k.icon}"></span>`:""}
                                ${k.label?k.label:k.value}
                            </button>`.trim();a.appendChild(m)});let l=b.querySelector(".dropdown__empty");l.style.display="";if(1>f.length){const k=`<i>"</i>${b.querySelector(".dropdown__search-box .form-control__input").value} tidak ditemukan<i>"</i>`,m=l.querySelector(".dropdown__empty-information .dropdown__empty-title");m&&(m.innerHTML=k);l.style.display="flex"}}})()}else f=!1}setInputSearch(e="default"){let f=this.element.nextElementSibling?.querySelector(".dropdown__search");f&&(f.classList.remove("error"),
f.classList.remove("loading"),"error"==e?f.classList.add("error"):"loading"==e&&f.classList.add("loading"));"autocomplete"==this.type&&this.setSelect(e)}setSelect(e="default"){let f=this.element.nextElementSibling?.closest(".dropdown");f&&(f.classList.remove("error"),f.classList.remove("loading"),"error"==e?f.classList.add("error"):"loading"==e&&f.classList.add("loading"))}}
(()=>{const e=b=>{if(b.matches(".form-control__input")&&b.closest(".dropdown__search-box")&&!b.querySelector("[data-dropdown-list='dynamic']")){var a=b.closest(".dropdown");if(a){let c=!0;a.querySelectorAll(".dropdown__list > .dropdown__item").forEach(d=>{0<=d.textContent.trim().toLowerCase().indexOf(b.value.trim().toLowerCase())||0<=d.dataset.alt?.trim().toLowerCase().indexOf(b.value.trim().toLowerCase())?(d.style.display="",c=!1):d.style.display="none"});if(a=a.querySelector(".dropdown__empty"))if(a.style.display=
"",c){const d=`<i>"</i>${b.value} tidak ditemukan<i>"</i>`,l=a.querySelector(".dropdown__empty-information .dropdown__empty-title");l&&(l.innerHTML=d);a.style.display="flex"}}}},f=(b="dropdown__box")=>{document.querySelectorAll(".dropdown").forEach(a=>{let c=a.querySelector('[data-toggle="dropdown"]'),d=a.querySelector(".dropdown__box");a=a.querySelector(".dropdown__list");let l=!1;"dropdown__box"==b?l=d:"dropdown__list"==b&&(l=a);l&&(l.classList.remove("show"),l.style.inset="",l.style.transform=
"",c?.setAttribute("aria-expanded",!1),c?.classList.remove("show"))})};document.addEventListener("click",b=>{var a=b.target;a.closest(".dropdown")?.querySelector(".dropdown__box.show")||f("dropdown__box");a.closest(".dropdown")?.querySelector(".dropdown__list.show")||f("dropdown__list");if(a.closest('[data-toggle="dropdown"]:not(:disabled)')){let u=a.closest(".dropdown"),w=a.closest('[data-toggle="dropdown"]');var c=u.querySelector(".dropdown__box"),d=u.querySelector(".dropdown__list");b="";document.querySelectorAll(".dropdown").forEach(y=>
{y!==u&&(y.querySelector(".dropdown__box")?.classList.remove("show"),y.querySelector(".dropdown__list")?.classList.remove("show"),w?.setAttribute("aria-expanded",!1))});c?(c.classList.toggle("show"),b=c):d&&(d.classList.toggle("show"),b=d);if(b.classList.contains("show")){w?.setAttribute("aria-expanded",!0);w?.classList.add("show");b?.querySelector("input.form-control__input")?.focus();c=document.body.getBoundingClientRect();d=b.getBoundingClientRect();var l=d.top-c.top;(window.innerHeight>=d.height||
l+d.height>=c.height)&&d.top+d.height>=window.innerHeight-1&&(b.style.top="unset",b.style.bottom="calc(100% + 0.25rem)")}else w?.setAttribute("aria-expanded",!1),w?.classList.remove("show")}a.closest(".dropdown")&&a.closest('[data-clear="input"]')&&(a.closest(".dropdown").querySelector(".form-control__input").value="",a.closest(".dropdown").querySelector(".form-control__input").focus(),e(a.closest(".dropdown").querySelector(".form-control__input")));if(a.closest(".dropdown__item")){var k=a.closest(".dropdown");
b=k.querySelector('[data-toggle="dropdown"]');var m=k.querySelector(".dropdown__selected");a=a.closest(".dropdown__item");c=a.querySelector("a");d=a.querySelector("button");var q=k.querySelectorAll(".dropdown__item");l=k.querySelector(".dropdown__box");var v=k.querySelector(".dropdown__list");let u="";l?u=l:v&&(u=v);if(d&&!d.disabled&&m&&(q.forEach(w=>{w.classList.remove("selected")}),a.classList.add("selected"),m.innerHTML=d.innerHTML,k=k.parentNode.querySelector("select"),m=a?.dataset.value,k&&
void 0!==m)){q=!1;for(v=0;v<k.options.length;v++)if(k.options[v].value===m){q=!0;break}q||(q=document.createElement("option"),q.value=m,q.innerHTML=d?.innerHTML,k.appendChild(q));k.value=a?.dataset.value}(c&&!c.disabled||d&&!d.disabled)&&(!l?.classList.contains("dropdown__box_multi")||a.closest(".dropdown__list_hidden"))&&u&&(u.classList.remove("show"),u.classList.contains("show")?b?.setAttribute("aria-expanded",!0):b?.setAttribute("aria-expanded",!1),b?.focus())}});const h=(b=null,a=null)=>{if(a&&
a.closest(".dropdown_nav")&&null==b||b&&null==a){b=b??a.closest(".dropdown_nav");const c=b.querySelector(".dropdown__box")??b.querySelector(".dropdown__list");setTimeout(()=>{c&&void 0==c.dataset.popperPlacement&&c.getBoundingClientRect().right>window.innerWidth-24&&(c.dataset.popperPlacement="bottom-right")},10)}},g=()=>{document.querySelectorAll(".dropdown_nav").forEach(b=>{h(b)})};document.addEventListener("DOMContentLoaded",()=>{g()});document.addEventListener("click",b=>{h(null,b.target)});document.addEventListener("keydown",
b=>{"Escape"===b.key&&(f("dropdown__box"),f("dropdown__list"))});document.addEventListener("focusin",b=>{b=b.target;b.closest(".dropdown")?.querySelector(".dropdown__box.show")||f("dropdown__box");b.closest(".dropdown")?.querySelector(".dropdown__list.show")||f("dropdown__list")});document.addEventListener("input",b=>{e(b.target)});window.addEventListener("resize",()=>{document.querySelectorAll(".dropdown__box.show").forEach(b=>{b.parentNode.querySelector('[data-toggle="dropdown"]')});document.querySelectorAll(".dropdown__list.show").forEach(b=>
{b.parentNode.querySelector('[data-toggle="dropdown"]')});g()});window.addEventListener("scroll",()=>{document.querySelectorAll(".dropdown__box.show").forEach(b=>{b.parentNode.querySelector('[data-toggle="dropdown"]')});document.querySelectorAll(".dropdown__list.show").forEach(b=>{b.parentNode.querySelector('[data-toggle="dropdown"]')})})})();
const getValueWidth=(e,f="value")=>{const h=document.createElement("span");h.className="dropdown__tag-hidden";h.innerText="value"==f?e.value:e.placeholder;e.closest(".dropdown__tag-input").appendChild(h);f=h.offsetWidth;e.closest(".dropdown__tag-input").removeChild(h);return f+12};document.addEventListener("click",e=>{e=e.target;e.closest(".dropdown__tag")&&e.closest(".dropdown__tag").querySelector("input")?.focus()});
const setwidthDropdownTagInput=e=>{e.closest(".dropdown__tag-input")&&(e=e.closest(".dropdown__tag-input").querySelector("input"),e.style.width=getValueWidth(e)+"px",e.style.maxWidth=getValueWidth(e)+"px")};document.addEventListener("input",e=>{setwidthDropdownTagInput(e.target)});
document.addEventListener("DOMContentLoaded",function(){document.body.querySelectorAll(".dropdown__tag-input input").forEach(e=>{e.style.minWidth=getValueWidth(e,"placeholder")+"px";e.style.maxWidth=getValueWidth(e,"placeholder")+"px"})});function adjustWidth(e){e&&(e.style.width="auto",e.style.width=`${e.scrollWidth}px`)}window.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".dropdown__tag-input input");adjustWidth(e)});document.addEventListener("DOMContentLoaded",function(){var e=document.querySelectorAll(".select-search");for(let h=0;h<e.length;++h){var f=e[h];const g=new Choices(f,{allowHTML:!0,shouldSort:!1,placeholderValue:f.dataset.placeholder??"",searchPlaceholderValue:f.dataset.searchPlaceholder??""});f.qnChoices=g}(function(h){document.querySelectorAll(h).forEach(function(g){let b=new Choices(g,{allowHTML:!0,shouldSort:!1,searchEnabled:!1,removeItemButton:!1});g.qnChoices=b})})(".select-default");(function(h){document.querySelectorAll(h).forEach(function(g){var b=
new Choices(g,{allowHTML:!0,shouldSort:!1});g.qnChoices=b})})(".select-multiple-without-remove");(function(h){document.querySelectorAll(h).forEach(function(g){var b=new Choices(g,{allowHTML:!0,shouldSort:!1,delimiter:",",editItems:!0,maxItemCount:g.dataset.maxItemCount??-1,removeItemButton:!0});g.qnChoices=b})})(".select-multiple");(function(h,g){document.querySelectorAll(h).forEach(function(b){(new Choices(b,{allowHTML:!1,shouldSort:!1,placeholder:!0,placeholderValue:"Pick a Strokes record",maxItemCount:5})).setChoices(function(){return fetch(g).then(function(a){return a.json()}).then(function(a){return a.releases.map(function(c){return{value:c.title,
label:c.title}})})})})})(".select-multiple-remote-fetch","https://api.discogs.com/artists/55980/releases?token=QBRmstCkwXEvCjTclCpumbtNwvVkEzGAdELXyRyW");(function(h,g,b){document.querySelectorAll(h).forEach(function(a){(new Choices(a,{allowHTML:!1,shouldSort:!1,searchPlaceholderValue:"Search for an Arctic Monkeys record"})).setChoices(function(){return fetch(g).then(function(c){return c.json()}).then(function(c){return c.releases.map(function(d){return{label:d.title,value:d.title}})})}).then(function(c){c.setChoiceByValue(b)})})})(".select-single-remote-fetch",
"https://api.discogs.com/artists/391170/releases?token=QBRmstCkwXEvCjTclCpumbtNwvVkEzGAdELXyRyW","Fake Tales Of San Francisco")});
(()=>{const e=h=>{const g=h.closest(".choices");var b=h.getBoundingClientRect();const a=document.body.getBoundingClientRect();b=b.bottom>=a.bottom-1;!f(h,["absolute","fixed","sticky"])&&b&&g.classList.add("is-flipped");g&&(h=g.querySelector(".choices__inner"))&&!g.hasQnEventClick&&(h.addEventListener("click",c=>{const d=c.target,l=d.closest(".choices:not(.is-open)");if(l){const k=l.querySelector(".choices__list.choices__list--dropdown");k&&(k.style.opacity=0,setTimeout(()=>{f(d,["absolute","fixed",
"sticky"])||0>k.getBoundingClientRect().top&&l.classList.remove("is-flipped");k&&(k.style.opacity="")},10))}}),g.hasQnEventClick=!0)};(new MutationObserver(h=>{h.forEach(g=>{"childList"===g.type&&(g=g.target,g.classList.contains("choices__list--dropdown")&&e(g))})})).observe(document.body,{childList:!0,subtree:!0});const f=(h,g=[])=>{for(h=h.parentElement;h;){const b=window.getComputedStyle(h).position;if(g.includes(b))return!0;h=h.parentElement}return!1}})();(()=>{const e=(g,b,a=!1)=>{a&&(b.innerHTML="");g.querySelectorAll("a, button").forEach(c=>{if(!c.closest('[data-toggle="dropdown"]')&&!c.closest('[data-dropdown-group="show"]')&&!c.closest(".dropdwon__item")){const l=document.createElement("div");l.classList="dropdown__item";let k=c.cloneNode(!0);var d=Array.from(k.classList).filter(m=>m.startsWith("btn_"));k.classList.remove("btn");d.forEach(m=>{k.classList.remove(m)});if(d=k.getAttribute("aria-label")??k.dataset.tooltip??k.dataset.btnLabel)k.innerHTML+=
d;l.append(k);b.append(l)}c.closest(".dropdwon__item")&&(c=c.closest(".dropdwon__item").cloneNode(!0),b.append(c))})},f=g=>{var b=g.querySelector(".dropdown-group__target"),a=g.querySelector(".dropdown-group__toggle");a&&(a.querySelectorAll("a, button").forEach(c=>{c.dataset.toggle="dropdown"}),a=a.innerHTML.trim(),b.classList="dropdown",b.dataset.dropdownGroup="show",b.innerHTML=`
                ${a}
                <div class="dropdown__list dropdown__list_menu-end"></div>
            `.trim(),b=b.querySelector(".dropdown__list"),e(g,b))},h=()=>{document.querySelectorAll(".dropdown-group").forEach(g=>{f(g)})};document.addEventListener("DOMContentLoaded",g=>{h()});(new MutationObserver(g=>{g.forEach(b=>{"childList"===b.type&&0<b.addedNodes.length&&(b=Array.from(b.addedNodes).filter(a=>a.classList&&a.classList.contains("dropdown-group")),0<b.length&&b.forEach(a=>{f(a)}))})})).observe(document.body,{childList:!0,subtree:!0})})();(()=>{document.addEventListener("click",e=>{e=e.target;if(e.matches("[data-clear='input']")){var f=e.parentNode;f&&(f=f.querySelector(".form-control__input"))&&(f.value="")}e.matches("[data-visibility='input']")&&(f=e.parentNode,e=f.querySelector("[data-visibility='input']"),f&&(f=f.querySelector("input"),"text"==e.dataset.type?(f.type="password",e.dataset.type="password"):(f.type="text",e.dataset.type="text")))})})();
document.addEventListener("DOMContentLoaded",()=>{"xs sm md lg xl xxl".split(" ").forEach(e=>{document.querySelectorAll(`.form-control_expand-${e}`).forEach(f=>{f=f.querySelector("input");f.addEventListener("focus",h=>{h.target.closest(".form-control").classList.add("form-control_expanded")});f.addEventListener("focusout",h=>{h.target.closest(".form-control").classList.remove("form-control_expanded")})})})});
(()=>{const e=(b,a=!0)=>{const c=b.classList.contains("upload-draggable__file-input");b=b.closest(".upload-draggable");c&&b&&(a?b.classList.add("is-active"):b.classList.remove("is-active"))},f=b=>{const a=b.parentNode,c=a.parentNode.querySelector(".upload-draggable__success");a.style.opacity=0;c.style.display="flex";const d=b.files.length;1===d?c.innerHTML=`<span>${b.value.split("\\").pop()}</span>`:1<d?c.innerHTML="<span>"+d+" berkas</span> dipilih":(a.style.opacity=1,c.style.display="none")},h=
b=>{b.classList.contains("upload-draggable__file-input")&&(b.hasQnEventChange||(b.addEventListener("change",a=>{f(a.target)}),b.hasQnEventChange=!0),f(b))},g=function(b,a){let c;return function(...d){clearTimeout(c);c=setTimeout(()=>b.apply(this,d),a)}}(b=>{b.hasQnEventChange||(b.addEventListener("change",a=>{f(a.target)}),b.hasQnEventChange=!0)},100);(new MutationObserver(b=>{b.forEach(a=>{"childList"===a.type&&(a=a.target,a.classList.contains("upload-draggable__file-input")&&g(a),a.closest(".upload-draggable__file-input")&&
g(a.closest(".upload-draggable__file-input")),a=a.querySelectorAll(".upload-draggable__file-input"),0<a.length&&a.forEach(c=>{g(c)}))})})).observe(document.body,{childList:!0,subtree:!0});document.addEventListener("click",b=>{var a=b.target;e(a,!0);b=a.closest(".attachment");a=a.closest("[data-dismiss='attachment']");b&&a&&b.remove()});document.addEventListener("focusin",b=>{e(b.target,!0)});document.addEventListener("dragenter",b=>{e(b.target,!0)});document.addEventListener("drop",b=>{e(b.target,
!1)});document.addEventListener("focusout",b=>{e(b.target,!1)});document.addEventListener("dragleave",b=>{e(b.target,!1)});document.addEventListener("change",b=>{h(b.target)})})();var phonenumber=document.getElementById("phone-number");phonenumber&&phonenumber.addEventListener("keyup",function(e){phonenumber.value=phoneFormat(this.value)});
function phoneFormat(e,f){e=e.replace(/[^,\d]/g,"").toString().split(" ");var h=e[0].length%4,g=e[0].substr(0,h),b=e[0].substr(h).match(/\d{4}/gi);b&&(separator=h?" ":"",g+=separator+b.join(" "));g=void 0!=e[1]?g+" "+e[1]:g;return void 0==f?g:g?"+62 "+g:""};(()=>{const e=g=>{g.classList.add("on-closing");setTimeout(()=>{g.classList.remove("on-closing");g.classList.remove("is-visible")},450)},f=g=>{var b=g.target;const a=b.closest('[data-toggle="modal"]'),c=a?.getAttribute("data-target");if(a&&c){g.preventDefault();const d=document.querySelector(c);d&&!d.classList.contains("is-visible")&&(d.classList.add("on-opening"),setTimeout(()=>{d.classList.remove("on-opening");d.classList.add("is-visible")},10))}g=b.closest('[data-dismiss="modal"]');b=b.closest(".modal");
g&&b&&e(b)},h=g=>{"Escape"===g.key&&document.querySelectorAll(".modal.is-visible").forEach(b=>{e(b)})};document.addEventListener("click",g=>{f(g)});document.addEventListener("keydown",g=>{h(g)})})();class Pagination{constructor(e,f={}){this.element=e;this.url=this.element?.dataset.pageUrl?this.element.dataset.pageUrl:f?.url??"";this.stringification=this.element?.dataset.pageStringification?this.element.dataset.pageStringification:f?.stringification??"<<$page>>";this.total=this.element?.dataset.pageTotal?this.element.dataset.pageTotal:f?.total??1;this.current=this.element?.dataset.pageCurrent?this.element.dataset.pageCurrent:f?.current??1;this.pageLimit=this.element?.dataset.pageLimit?this.element.dataset.pageLimit:
f?.limit??7;this.lang={previous:f?.lang?.previous??"Previous",next:f?.lang?.next??"Next",page:f?.lang?.page??"Page",of:f?.lang?.of??"of"};this.prevText=f?.prevText??this.lang?.previous;this.nextText=f?.nextText??this.lang?.next;this.init()}init(){this.total=parseInt(this.total);this.current=parseInt(this.current);this.pageLimit=Math.floor(parseInt(this.pageLimit));this.pageLimit=0==this.pageLimit%2?this.pageLimit+1:this.pageLimit;this.element.style.display="none";const e=document.createElement("div");
e.className="pagination";const f=a=>`<li class="pagination__item${this.current==a?" active":""}"><a href="${this.linkPage(a)}"${this.current==a?' onclick="return false;"':""}>${a}</a></li>`;var h=()=>'<li class="pagination__ellipsis">...</li>';e.innerHTML=1>=this.current?e.innerHTML+`<button class="pagination__button-previous" aria-label="${this.prevText}" disabled><span class="pagination__button-text"${0==this.prevText?' style="display: none;"':""}>${this.prevText}</span></button>`:e.innerHTML+`<button class="pagination__button-previous" aria-label="${this.prevText}" onclick="window.location.href='${this.linkPage(this.current-
1)}'"><span class="pagination__button-text"${0==this.prevText?' style="display: none;"':""}>${this.prevText}</span></button>`;if(0<this.total){let a=document.createElement("ul");a.className="pagination__list";a.dataset.mobileText=`${this.lang.page} ${this.current} ${this.lang.of} ${this.total}`;var g=Math.floor(this.pageLimit/2);let c=this.total-g;var b=g-2;let d=this.current-b;b=this.current+b;a.innerHTML+=f(1).trim();if(1<this.total)if(1<this.total&&this.total<=this.pageLimit)for(h=2;h<=this.total;h++)a.innerHTML+=
f(h).trim();else if(this.current<=1+g){for(g=2;g<=this.pageLimit-2;g++)a.innerHTML+=f(g).trim();a.innerHTML+=h();a.innerHTML+=f(this.total).trim()}else if(this.current>c)for(a.innerHTML+=h(),h=c;h<=this.total;h++)a.innerHTML+=f(h).trim();else{if(this.current<=this.total)for(a.innerHTML+=h(),g=d;g<=b;g++)a.innerHTML+=f(g);a.innerHTML+=h();a.innerHTML+=f(this.total).trim()}e.appendChild(a)}else e.innerHTML+=f(1).trim();e.innerHTML=this.current>=this.total?e.innerHTML+`<button class="pagination__button-next" aria-label="${this.nextText}" disabled><span class="pagination__button-text"${0==
this.nextText?' style="display: none;"':""}>${this.nextText}</span></button>`:e.innerHTML+`<button class="pagination__button-next" aria-label="${this.nextText}" onclick="window.location.href='${this.linkPage(this.current+1)}'"><span class="pagination__button-text"${0==this.nextText?' style="display: none;"':""}>${this.nextText}</span></button>`;this.element.after(e)}linkPage(e){return this.url.replace(this.stringification,e)}};(()=>{const e=(a,c=!1)=>{const d=a.querySelector(".progress__bar"),l=a.querySelector(".progress__percentage");let k=d.dataset.percentStart??0,m=d.dataset.percentEnd??100;k=parseInt(k);m=parseInt(m);c||(l&&(l.textContent=k+"%"),a.style.setProperty("--qn-progress-percent",k+"%"));setTimeout(()=>{l&&(l.textContent=m+"%");a.style.setProperty("--qn-progress-percent",m+"%")},c?150:0)},f=()=>{document.querySelectorAll(".progress").forEach(a=>{e(a)})},h=a=>{var c=a.querySelector(".progress-circle__bar");
a.querySelector("svg circle")||(a.innerHTML+="<svg><circle></circle><circle></circle></svg>");c=c.dataset.percentEnd;c=parseInt(c);a.style.setProperty("--progress-circle-percent",98*c/100);0>=c?(a.style.setProperty("--progress-dashoffset-end",1),c=0):100<=c?(a.style.setProperty("--progress-dashoffset-end",""),a.style.setProperty("--progress-circle-percent",102),c=100):a.style.setProperty("--progress-dashoffset-end","");a.querySelector(".progress-circle__number").textContent=c+"%";a.querySelector("svg circle:nth-child(2)").classList.add("animation")},
g=()=>{document.querySelectorAll(".progress-circle").forEach(a=>{h(a)})};document.addEventListener("DOMContentLoaded",a=>{f();g()});const b=a=>{a.nodeType===Node.ELEMENT_NODE&&a.querySelectorAll(".progress").forEach(c=>{e(c)})};(new MutationObserver(a=>{a.forEach(c=>{"childList"===c.type&&0<c.addedNodes.length&&(c=Array.from(c.addedNodes),c.filter(d=>d.classList&&d.classList.contains("progress")),c.forEach(d=>{d.classList&&d.classList.contains("progress")?e(d):b(d)}),c=c.filter(d=>d.classList&&d.classList.contains("progress-circle")),
0<c.length&&c.forEach(d=>{h(d)}))})})).observe(document.body,{childList:!0,subtree:!0});(new MutationObserver(a=>{a.forEach(c=>{if("attributes"===c.type&&"data-percent-end"===c.attributeName){c=c.target;const d=c.closest(".progress");d&&e(d,!0);(c=c.closest(".progress-circle"))&&h(c)}})})).observe(document.body,{attributes:!0,subtree:!0,attributeOldValue:!0,attributeFilter:["data-percent-end"]})})();const getElmInnerSize=(e,f=!1)=>{const h=getComputedStyle(e);let g=e.clientWidth;e=e.clientHeight;g-=parseFloat(h.paddingLeft)+parseFloat(h.paddingRight);e-=parseFloat(h.paddingTop)+parseFloat(h.paddingBottom);f&&(g+=parseFloat(h.borderLeft)+parseFloat(h.borderRight),e+=parseFloat(h.borderTop)+parseFloat(h.borderBottom));return{width:g,height:e}};
(()=>{function e(b,a){let c;return function(...d){clearTimeout(c);c=setTimeout(()=>b.apply(this,d),a)}}const f=b=>{const a=b.closest("table"),c=b.closest(".check-all-item");a&&c&&a.querySelectorAll(".check-item:not([disabled])").forEach(d=>{d.checked=c.checked})};document.addEventListener("click",b=>{var a=b.target;f(a);b=a.closest("table");a=a.closest(".check-item");if(b&&a){a=b.querySelector(".check-all-item");const c=b.querySelectorAll(".check-item:not([disabled])");b=b.querySelectorAll(".check-item:checked");
a.checked=!1;c.length===b.length&&(a.checked=!0)}});const h=b=>{const a=l=>{if(b){const q=(v,u,w=!1)=>{v.clientWidth>u.clientWidth?(u.classList.add("table-max_absolute"),v.querySelectorAll(".cell-action").forEach(y=>{y.style.height=y.closest("tr").offsetHeight+"px";y.style.maxHeight=y.closest("tr").offsetHeight+"px"})):(u.classList.remove("table-max_absolute"),u.setAttribute("style",""),w&&q(v,u))};q(l,b,!0)}l=l.querySelectorAll("tr");b&&b.classList.contains("table-max_absolute")&&b.style.setProperty("--qn-table-cell-action-width",
"fit-content");let k=0,m=0;l.forEach(q=>{q.classList.contains("row-skip")&&(m+=q.clientHeight);var v=q.querySelector(".cell-action");if(v){const u=getComputedStyle(v);v=parseFloat(u.paddingLeft)+parseFloat(u.paddingRight);let w=0;q.querySelectorAll(".cell-action > *").forEach((y,p)=>{w+=y.clientWidth;0<p?w+=parseFloat(u.gap):""});q=v+w;q>k&&(k=q)}});b?(b.style.setProperty("--qn-table-cell-action-width",k+"px"),b.style.setProperty("--qn-table-shadow-right-bottom-offset",m+"px"),0==k&&(b.style.setProperty("--qn-table-shadow-right-bottom-offset",
""),b.style.setProperty("--qn-table-cell-action-alone-width","8px"),b.style.setProperty("--qn-table-shadow-right-translate-x","8px"))):b.style.setProperty("--qn-table-cell-action-width","")},c=b.querySelector("table");if(c){const l=e(k=>a(k),100);var d=()=>{l(c)};l(c);b.hasQnInWindowResize||(window.addEventListener("resize",d),b.hasQnInWindowResize=!0)}d=l=>{l=l.target;const k=l.closest(".table-max"),m=l.closest(".table-max_absolute");k&&m&&l.querySelector("table")&&(k.scrollLeft+k.clientWidth>=k.scrollWidth-
1?m.classList.add("table-max_without-right-shadow"):m.classList.remove("table-max_without-right-shadow"),0<k.scrollLeft?m.classList.add("table-max_with-left-shadow"):m.classList.remove("table-max_with-left-shadow"))};b.hasQnEventScroll||(b.addEventListener("scroll",d),b.hasQnEventScroll=!0)};document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll(".table-max").forEach(b=>{h(b)})});const g=e(b=>h(b),100);(new MutationObserver(b=>{b.forEach(a=>{"childList"===a.type&&(a=a.target,
a.classList.contains("table-max")&&g(a),a.closest(".table-max")&&g(a.closest(".table-max")),a=a.querySelectorAll(".table-max"),0<a.length&&a.forEach(c=>{g(c)}))})})).observe(document.body,{childList:!0,subtree:!0});document.addEventListener("DOMContentLoaded",()=>{const b=c=>{a(c.target)},a=c=>{let d=Math.max(document.documentElement.clientHeight||0,window.innerHeight||0);const l=c.closest(".choices");c=c.closest(".table-max_absolute")||c.closest(".table-responsive");if(l&&c){const k=l.querySelector(".choices__list.choices__list--dropdown");
if(k){k.getBoundingClientRect();"true"!=l.dataset.listenerAlt&&window.addEventListener("scroll",()=>{l.getBoundingClientRect().top<k.offsetWidth&&l.classList.remove("is-flipped")});const m=()=>{const q=l.getBoundingClientRect();k.removeAttribute("style");k.style.height="fit-content";k.style.position="fixed";k.style.zIndex="1000";k.style.transition="inset 0s linear";k.style.left=`${q.x}px`;k.style.top=`${q.y+q.height}px`;k.style.bottom="";k.style.width=`${l.offsetWidth}px`;l.classList.contains("is-flipped")&&
(k.style.zIndex="1010",k.style.top="",k.style.bottom=`${d-q.y}px`,k.style.borderRadius=".5rem")};m();"true"!=l.dataset.listenerAlt&&(c.addEventListener("scroll",q=>{document.body.click()}),c.addEventListener("scroll",m),window.addEventListener("scroll",m));l.dataset.listenerAlt="true"}}};document.querySelectorAll(".table-responsive .choices, .table-max_absolute .choices").forEach(c=>{a(c)});document.addEventListener("click",b);document.addEventListener("focusin",b)})})();(()=>{const e=h=>{if(h=h.closest('[data-toggle="tab"]:not(.disabled)')){const g=h.dataset.target;h.parentNode.querySelectorAll('[data-toggle="tab"]').forEach(b=>{b.classList.remove("active");document.querySelectorAll(b.dataset.target).forEach(a=>a.classList.remove("active"))});h.classList.add("active");document.querySelectorAll(g).forEach(b=>b.classList.add("active"))}},f=()=>{const h=document.querySelectorAll('[data-toggle="tab"].active');h.length&&h.forEach(g=>{const b=document.querySelectorAll(g.dataset.target);
g.classList.add("active");b.forEach(a=>a.classList.add("active"))})};document.addEventListener("click",h=>{e(h.target)});document.addEventListener("DOMContentLoaded",()=>{f()})})();(()=>{document.addEventListener("click",e=>{var f=e.target;e=f.closest(".tag");f=f.closest("[data-dismiss='tag']");e&&f&&e.remove()})})();