"""
One-off customization layered on top of v1/unit-kerja.html (auto-generated by
build_mockup.py from mockups/raw/Kerjasama/"...Daftar Unit Kerja.html").

Request: bring the SPMI module's own Unit Kerja page
(mockups/raw/SPMI/"...Unit Kerja.html", captured from /v2/spmi/unit-kerja)
onto Kerjasama's Unit Kerja page - full 3-level hierarchy (Universitas ->
Fakultas -> Program Studi / Unit Non Akademik) and per-row "eye" preview,
data taken directly from SPMI's own capture (not just Kerjasama's flat
81-row list, which never included standalone Universitas/Fakultas records)
- but built with Kerjasama's own UI components, not SPMI's:
  - toggle/action icons use this app's own `sym sym-*` icon font and
    `btn btn-icon ... btn-outline-secondary btn-sm` button style (same
    pattern as the "Detail" button on v1/mitra.html), not SPMI's
    `icon icon-*-solid` / `btn_outline btn_xs` classes
  - status badge reuses the `badge-outline-success`/`badge-outline-danger`
    badges already used elsewhere in this same table
  - the "data ini cuma prodi & unit non akademik" disclaimer banner is
    dropped - it no longer applies once the full hierarchy (incl.
    Universitas/Fakultas) is shown
  - parent-row backgrounds are shaded by depth (Universitas > Fakultas >
    plain) so the hierarchy reads at a glance - SPMI itself uses the same
    flat gray at every depth, which is the "row color" this was asked to
    improve on

Eye/edit actions link to v1/unit-kerja-detail.html / v1/unit-kerja-edit.html
(built by build_unit_kerja_detail_edit.py, run separately - see that
script's docstring) - every row points at the same single pair of pages,
same accepted limitation as Mitra's own list. (Earlier revision: no detail
page existed yet, so eye opened a generic preview modal and edit was an
inert enabled button - both dropped once real pages existed to link to.)

This is a hand-authored transformation, not something build_mockup.py's
generic per-page pipeline can derive - re-run this script after
unit-kerja.html if it's ever rebuilt from a fresh capture (build_mockup.py
would silently overwrite this customization otherwise, per this repo's
"never hand-edit generated pages, only sanctioned scripts touch them" rule).
Re-running this AFTER build_unit_kerja_detail_edit.py is safe - the action
links it builds already point at the real pages, nothing to redo.

Usage:
    python mockups/scripts/customize_unit_kerja.py
"""
from pathlib import Path

from bs4 import BeautifulSoup, NavigableString

ROOT = Path(__file__).resolve().parents[2]
PAGE = ROOT / "v1" / "unit-kerja.html"
SPMI_RAW = ROOT / "mockups" / "raw" / "SPMI" / "SEVIMA Platform - Unit Kerja.html"

# Column headers matched to SPMI's own wording exactly (Kerjasama originally
# had its own shorter labels - "Kode Unit", "Nama Unit", "Apakah Aktif",
# "Jenis Unit" - keyed here by the OLD label so relabel_headers() can find
# and replace them idempotently on a fresh build; also reused as the
# preview modal's field labels so both stay consistent).
COLUMN_LABELS = {
    "Kode Unit": "Kode Unit Kerja",
    "Nama Unit": "Nama Unit Kerja",
    "Apakah Aktif": "Status Keaktifan Unit Kerja",
    "Jenis Unit": "Kategori Unit Kerja",
}

# Depth 0 = Universitas (root), depth 1 = Fakultas / a unit sitting directly
# under Universitas, depth 2 = Program Studi / UPPS under a Fakultas.
# Depth 1 uses this app's own `.table-light` striped-row shade
# (--bs-table-striped-bg, already used for this table's own <thead>) rather
# than SPMI's literal #F8FAFC - noticeably darker/more visible, per request.
DEPTH_BG = {0: "#EAF1FE", 1: "#E9ECEE"}
DEPTH_INDENT_PX = 18  # per level, applied to the name cell

PREVIEW_SCRIPT = """// Expands/collapses a parent row's descendants (see
// customize_unit_kerja.py). Page-specific scaffolding, same spirit as
// mockup-interactions.js. The eye/edit actions are plain <a href> links to
// real pages (unit-kerja-detail.html / unit-kerja-edit.html, built by
// build_unit_kerja_detail_edit.py) - no JS needed for those.
(function () {
    document.addEventListener("click", function (event) {
        // Action links/buttons sit inside a row that may ALSO be a group
        // toggle (data-group-toggle on the <tr> itself) - let them navigate
        // normally instead of also collapsing/expanding the row.
        if (event.target.closest("a, button")) return;

        var toggle = event.target.closest("[data-group-toggle]");
        if (toggle) {
            var groupId = toggle.getAttribute("data-group-toggle");
            var icon = toggle.querySelector(".sym-chevron-up, .sym-chevron-down");
            var wasExpanded = icon && icon.classList.contains("sym-chevron-up");
            document.querySelectorAll('[data-ancestors~="' + groupId + '"]').forEach(function (row) {
                row.classList.toggle("d-none", wasExpanded);
            });
            if (icon) {
                icon.classList.toggle("sym-chevron-up", !wasExpanded);
                icon.classList.toggle("sym-chevron-down", wasExpanded);
            }
            // Same behavior as SPMI's own capture: the "(N unit)" count
            // only shows once the group is collapsed, hidden while expanded.
            var countEl = toggle.querySelector(".child-count-indicator");
            if (countEl) countEl.style.display = wasExpanded ? "" : "none";
        }
    });
})();
"""


def parse_spmi_tree():
    """SPMI's <tr data-id data-parent-id> rows aren't nested in the DOM (an
    HTML table can't nest <tr>s) - the hierarchy is purely
    id/parent-id-based. Returns a flat list of nodes in proper depth-first
    order (parent immediately followed by all its descendants), each with
    depth/ancestors computed, ready to render."""
    html = SPMI_RAW.read_text(encoding="utf-8", errors="ignore")
    soup = BeautifulSoup(html, "lxml")
    raw_rows = soup.find("table").find("tbody").find_all("tr")

    by_id, children_of, order = {}, {}, []
    for tr in raw_rows:
        node_id = tr.get("data-id")
        parent_id = tr.get("data-parent-id") or "0"
        tds = tr.find_all("td")
        kode, nama_td, status_td, kategori_td = tds[0], tds[1], tds[2], tds[3]
        # Parent rows wrap the name in <b>Name(N Prodi)</b> - grab that and
        # strip the count (recomputed from the actual children below
        # instead). Leaf rows have no <b>: just an empty width:24px spacer
        # <span> followed by the real name in a second <span> - take the
        # LAST span, not the first (find("span") alone grabs the spacer).
        nama = nama_td.find("b") or nama_td.find_all("span")[-1]
        nama_text = nama.get_text(strip=True).split("(")[0].strip()
        node = {
            "id": node_id, "parent_id": parent_id,
            "kode": kode.get_text(strip=True),
            "nama": nama_text,
            "aktif": status_td.get_text(strip=True),
            "jenis": kategori_td.get_text(strip=True),
        }
        by_id[node_id] = node
        children_of.setdefault(parent_id, []).append(node_id)
        order.append(node_id)  # first-seen order, used to keep siblings sorted as captured

    def walk(node_id, depth, ancestors):
        node = dict(by_id[node_id])
        node["depth"] = depth
        node["ancestors"] = ancestors
        node["child_ids"] = children_of.get(node_id, [])
        result = [node]
        for child_id in children_of.get(node_id, []):
            result.extend(walk(child_id, depth + 1, ancestors + [node_id]))
        return result

    roots = [n for n in order if by_id[n]["parent_id"] == "0"]
    nodes = []
    for root_id in roots:
        nodes.extend(walk(root_id, 0, []))
    return nodes


def badge_html(status_text):
    cls = "badge-outline-success" if status_text == "Aktif" else "badge-outline-danger"
    return f'<div class="w-100 d-flex justify-content-center"><span class="badge {cls} badge-sm">{status_text}</span></div>'


def build_action_cell(soup, node):
    """Eye/edit link to the real Detail/Edit pages (built by
    build_unit_kerja_detail_edit.py from one sample record) - every row
    points at the same single pair of pages, same accepted limitation as
    Mitra's own list (every row's eye icon there also points at the one
    static mitra-detail.html, not per-id data). Previously the eye button
    opened a generic preview modal and edit was an inert enabled button;
    both were superseded once real Detail/Edit pages existed."""
    td = soup.new_tag("td")
    wrap = soup.new_tag("div", **{"class": "d-flex align-items-center justify-content-center gap-1"})
    btn_classes = ("btn btn-icon d-md-flex justify-content-center align-items-center "
                   "btn-outline-secondary btn-sm")

    eye_link = soup.new_tag("a", href="unit-kerja-detail.html", **{
        "class": btn_classes, "aria-label": "Preview",
    })
    eye_link.append(soup.new_tag("i", **{"class": "sym sym-eye-solid"}))
    wrap.append(eye_link)

    edit_link = soup.new_tag("a", href="unit-kerja-edit.html", **{
        "class": btn_classes, "aria-label": "Ubah",
    })
    edit_link.append(soup.new_tag("i", **{"class": "sym sym-pencil-solid"}))
    wrap.append(edit_link)

    # Delete stays disabled - matches SPMI's own capture, and unlike eye/edit
    # this wasn't asked to change (no delete page/flow exists either).
    delete_btn = soup.new_tag("button", type="button", disabled="", **{
        "class": btn_classes, "aria-label": "Hapus",
    })
    delete_btn.append(soup.new_tag("i", **{"class": "sym sym-trash-solid"}))
    wrap.append(delete_btn)

    td.append(wrap)
    return td


def build_row(soup, node):
    has_children = bool(node["child_ids"])
    group_id = f"unit-kerja-{node['id']}"
    attrs = {}
    if has_children:
        attrs["data-group-toggle"] = group_id
        # Plain `background-color` on a <tr> is invisible here: this table's
        # own CSS paints every *cell* with `background-color:var(--bs-table-bg)`
        # plus an `inset 0 0 0 9999px var(--bs-table-bg-state, ...,
        # var(--bs-table-accent-bg))` box-shadow, which fully covers
        # whatever the row itself is styled with. Setting these two custom
        # properties on the <tr> instead is Bootstrap 5's own supported way
        # to color a row (how .table-active/.table-light etc. work) - the
        # cells inherit them and actually render the tint. Verified directly
        # (Playwright) before relying on it.
        bg = DEPTH_BG.get(node["depth"], "#FFFFFF")
        attrs["style"] = f"--bs-table-bg:{bg};--bs-table-accent-bg:{bg};cursor:pointer"
    if node["ancestors"]:
        attrs["data-ancestors"] = " ".join(f"unit-kerja-{a}" for a in node["ancestors"])
    tr = soup.new_tag("tr", **attrs)

    td_kode = soup.new_tag("td")
    td_kode.string = node["kode"]
    tr.append(td_kode)

    td_nama = soup.new_tag("td")
    nama_wrap = soup.new_tag("div", **{
        "class": "d-flex align-items-center gap-2",
        "style": f"padding-left:{node['depth'] * DEPTH_INDENT_PX}px",
    })
    if has_children:
        nama_wrap.append(soup.new_tag("i", **{"class": "sym sym-chevron-up"}))
    else:
        nama_wrap.append(soup.new_tag("span", **{"style": "width:16px;display:inline-block"}))
    name_el = soup.new_tag("b") if has_children else soup.new_tag("span")
    name_el.string = node["nama"]
    nama_wrap.append(name_el)
    if has_children:
        # Matches SPMI's own behavior exactly: this count only shows while
        # the group is COLLAPSED (SPMI's own capture has it
        # `style="display: none;"` while expanded, which is the default
        # state here too - see toggle logic in PREVIEW_SCRIPT).
        count_span = soup.new_tag("span", **{
            "class": "text-secondary child-count-indicator", "style": "display:none",
        })
        count_span.string = f"({len(node['child_ids'])} unit)"
        nama_wrap.append(count_span)
    td_nama.append(nama_wrap)
    tr.append(td_nama)

    td_aktif = soup.new_tag("td")
    td_aktif.append(BeautifulSoup(badge_html(node["aktif"]), "lxml").div)
    tr.append(td_aktif)

    td_jenis = soup.new_tag("td")
    td_jenis.string = node["jenis"]
    tr.append(td_jenis)

    tr.append(build_action_cell(soup, node))
    return tr


def main():
    nodes = parse_spmi_tree()

    soup = BeautifulSoup(PAGE.read_text(encoding="utf-8"), "lxml")

    banner = soup.find("div", class_="alert-primary")
    if banner:
        banner.decompose()

    table = soup.find("table")
    thead_tr = table.find("thead").find("tr")
    # Idempotent against both a freshly-regenerated page (still has the
    # original "Parent Unit" column, no "Aksi") and an already-customized
    # one (Parent Unit already gone, Aksi already there) - so this script
    # can be re-run safely either way.
    for th in thead_tr.find_all("th"):
        if "parent unit" in th.get_text(strip=True).lower():
            th.decompose()
    aksi_th = next((th for th in thead_tr.find_all("th") if th.get_text(strip=True) == "Aksi"), None)
    if aksi_th is None:
        aksi_th = soup.new_tag("th")
        aksi_th.string = "Aksi"
        thead_tr.append(aksi_th)
    # Same convention already used for the "Aksi" header on v1/mitra.html -
    # reapplied every run (not just on first creation) so a page customized
    # before this alignment fix picks it up too.
    aksi_th["class"] = "cell-action text-center"
    aksi_th["style"] = "width: 80px"

    # Relabel to SPMI's own header wording (Kerjasama's originals were
    # shorter - see COLUMN_LABELS). Each th wraps its label text + a sort
    # icon in a <div class="d-flex gap-3"> - replace just the leading text
    # node, keep the icon. Matches by OLD label, so re-running this script
    # against an already-relabeled page is a no-op instead of erroring.
    for th in thead_tr.find_all("th"):
        wrapper = th.find("div", class_="d-flex")
        if wrapper is None:
            continue
        text_node = next((c for c in wrapper.children if isinstance(c, NavigableString)), None)
        if text_node and text_node.strip() in COLUMN_LABELS:
            text_node.replace_with(COLUMN_LABELS[text_node.strip()] + " ")

    tbody = table.find("tbody")
    tbody.clear()
    for node in nodes:
        tbody.append(build_row(soup, node))

    body = soup.body
    # Stale artifact from before eye/edit linked to real pages - remove if
    # this is re-run against a page still carrying the old preview modal.
    old_modal = soup.find(id="modal-preview-unit-kerja")
    if old_modal:
        old_modal.decompose()

    for old_script in soup.find_all("script", string=lambda s: s and "data-group-toggle" in s):
        old_script.decompose()
    script_tag = soup.new_tag("script")
    script_tag.string = PREVIEW_SCRIPT
    body.append(script_tag)

    PAGE.write_text(str(soup), encoding="utf-8")
    total = len(nodes)
    parents = sum(1 for n in nodes if n["child_ids"])
    print(f"Customized {PAGE.relative_to(ROOT)}: {total} rows from SPMI's own data "
          f"({parents} expandable, {total - parents} leaf).")


if __name__ == "__main__":
    main()
